motds:
  # Modern MOTD for newer client versions. (1.16 to latest)
  # - "" is a new line that will be shown for the motd or you can use the following ▼▼
  #
  # IMPORTANT:
  # To use gradients you will need the legacy format.
  #
  # Use '&' for color codes and '%newline%' for an additional line break within a single list item.
  modern:
    - "      &4▪▪  &x&9&7&0&0&0&0&lI&x&9&1&0&0&0&0&lM&x&8&A&0&0&0&0&lA&x&8&4&0&0&0&0&lN&x&7&D&0&0&0&0&lI&x&7&7&0&0&0&0&lT&x&7&0&0&0&0&0&lY &x&9&7&9&7&9&7&lN&x&9&1&9&1&9&1&lE&x&8&A&8&A&8&A&lT&x&8&4&8&4&8&4&lW&x&7&D&7&D&7&D&lO&x&7&7&7&7&7&7&lR&x&7&0&7&0&7&0&lK &8▸ &7「 1.16 - 1.21x 」 &4▪▪ %newline%&8➥ &x&B&0&7&8&2&E&lN&x&B&D&8&B&3&5&lO&x&C&A&9&E&3&C&lV&x&D&8&B&1&4&3&lE&x&E&5&C&3&4&9&lD&x&F&2&D&6&5&0&lA&x&F&F&E&9&5&7&lD &8┃ &x&7&F&8&0&7&DA&x&8&7&8&8&8&5p&x&8&F&9&0&8&Do&x&9&7&9&8&9&5y&x&9&F&A&0&9&Ea&x&A&7&A&8&A&6n&x&A&F&B&0&A&Eo&x&B&7&B&8&B&6s &x&B&F&C&0&B&Ed&x&C&7&C&7&C&6o&x&C&F&C&F&C&En&x&D&7&D&7&D&6a&x&D&F&D&F&D&Fn&x&E&7&E&7&E&7d&x&E&F&E&F&E&Fo &x&F&7&F&7&F&7e&x&F&F&F&F&F&Fn &x&B&0&7&8&2&E&nt&x&B&5&7&F&3&0&ni&x&B&9&8&5&3&3&ne&x&B&E&8&C&3&5&nn&x&C&3&9&3&3&8&nd&x&C&7&9&9&3&A&na&x&C&C&A&0&3&C&n.&x&D&1&A&7&3&F&ni&x&D&5&A&D&4&1&nm&x&D&A&B&4&4&4&na&x&D&E&B&A&4&6&nn&x&E&3&C&1&4&9&ni&x&E&8&C&8&4&B&nt&x&E&C&C&E&4&D&ny&x&F&1&D&5&5&0&n.&x&F&6&D&C&5&2&nl&x&F&A&E&2&5&5&no&x&F&F&E&9&5&7&nl"
  # Legacy MOTD for older client versions. (1.15 to 1.0)
  # - "" is a new line that will be shown for the motd or you can use the following ▼▼
  # Use '&' for color codes and '%newline%' for an additional line break within a single list item.
  legacy:
    - "&4&lIMANITY &F&lNETWORK &7| &8「 1.16 - 1.21x 」"
    - "&fServidor solo disponible para 1.16 en adelante!"
